### ISSUE TITLE
Misleading metric name kafka_topic:kafka_topic_partitions:count

### ISSUE THREAD

**Issue by k-wall** [bf2fc6cc711aee1a0c2a/kas-fleet-manager#688]
https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/0961e4b7cfd9f0ad2b99c8a0637e49cffcadad7f/internal/kafka/constants/metrics.go#L127

```
		"kafka_topic:kafka_topic_partitions:count": {
			Name:           "kafka_topic:kafka_topic_partitions:count",
			Help:           KafkaTopicPartitionsCountDesc,
			Type:           prometheus.GaugeValue,
			TypeName:       "GAUGE",
			VariableLabels: []string{},
		},
```

The metric name `kafka_topic:kafka_topic_partitions:count` is wrong.    What is being exposed is a count of the number of topics in the instance, not the number of topic_partitions.   Sure, underneath we are deriving this value from a expression using the metric `kafka_topic_partitions`, but that's implementation detail.  It does not belong in the API.

I'd also argue that `kafka_topic:kafka_topic_partitions:sum` would be more naturally called `kafka_topic:kafka_topic_partitions:count` because it is the count of the number of partitions.    Again the fact that it is derived from a sum expression it irrelevant to the API.

The metric descriptions are correct.

**Comment by machi1990** [comment]
@akoserwal you were looking at metrics name epic, is that correct? if so, will what you were looking at deal with cases like the one presented in this issue? I guess there is an opportunity of centralizing the metrics naming effort under that epic.

**Comment by akoserwal** [comment]
@machi1990, yes, thanks. I'll follow up

**Comment by machi1990** [comment]
Thanks @akoserwal

**Comment by machi1990** [comment]
I suppose this is covered by https://github.com/bf2fc6cc711aee1a0c2a/architecture/pull/64.
Is this correct @JameelB @k-wall ? If so, let's close the issue once that PR is merged.

**Comment by JameelB** [comment]
yes that's correct, but that's only the proposal, it won't be fully resolved yet. I think we should only close this once we actually have the new metric place. wdyt?

**Comment by machi1990** [comment]
Okay, that sounds good as well. Thanks @JameelB
